alias ls='eza --icons=always'
alias la='eza --icons=always -a'
alias ll='eza --icons=always -al'

alias vi='nvim'
alias vim='nvim'
alias nv='nvim'
alias oc='opencode'
alias y='yazi'

alias vi.='nvim .'
alias nvim.='nvim .'
alias vim.='nvim .'
alias oc.='oc .'
alias dotfiles='cd ~/.local/dotfiles/'
# Use pnpm as default package manager. To run the real npm:
#   \npm <command>       — backslash bypasses alias
#   command npm <command> — also bypasses alias
alias npm='pnpm'
